### ISSUE TITLE
Realtime factor or at least showing ctrl callback processing time

### ISSUE THREAD

**Issue by klowrey** [Lyceum/LyceumMuJoCoViz.jl#12]
can calculate the ratio of, ie mppi callback wrt to the timestep of the model advanced at each step, so we can track how much headroom we have for realtime interactive control.

Realtime Factor: 0.3 dt / 0.8 s = 0.375 

We'd want the factor to be > 1, but having the timings would be nice. dt in the above should be timestep*skip.

**Comment by colinxs** [comment]
post-release
