### ISSUE TITLE
help string causes major rendering slowdown

### ISSUE THREAD

**Issue by colinxs** [Lyceum/LyceumMuJoCoViz.jl#16]
Following up on #15: help string slows down rendering. It's either from:

1. `mjr_overlay`
2. from the generation of the string thats passed `mjr_overlay`

I'm guessing (1) since I only generate e.handlerdescription once when a mode if first entered (and do minimal strings transformations thereafter), but would be nice to confirm. If it is (2) that's good news since I can just cache the full help string (instead of just e.handlerdescription).

**Comment by klowrey** [comment]
It seems like the shorter the string the less of a slowdown there is.

You pass in info1 and info2 where info1 has more text. Passing in info2 twice increases FPS.
