### ISSUE TITLE
Not all mujoco visualization features are currently there

### ISSUE THREAD

**Issue by klowrey** [Lyceum/LyceumMuJoCoViz.jl#7]
`simulate.cpp` allows for pressing f to view forces and c to view contacts. This is done by moving through the appropriate static arrays in MuJoCo itself.

It would be nice to be consistent with simulate.cpp.

**Comment by klowrey** [comment]
Also the mouse commands are not the same; ctrl-middle click should change the camera to follow the clicked body for instance.

The commands are in simulate.jl from rlopt or simulate.cpp

**Comment by colinxs** [comment]
- [ ] forces
- [ ] contacts
- [ ] ctrl-middle click change cam to follow clicked body

**Comment by colinxs** [comment]
fixed in #22
