### ISSUE TITLE
Rendering is slow on non-nvidia GPUs.

### ISSUE THREAD

**Issue by klowrey** [Lyceum/LyceumMuJoCoViz.jl#8]
Only one instance so far; on my laptop the rendering is very slow. It speeds up a little with a smaller window but has trouble with passive dynamics or even trajectory playback at real-time speeds.

**Comment by colinxs** [comment]
I'm guessing simulate.cpp runs fine? 

Any other machines?

**Comment by klowrey** [comment]
simulate.cpp runs fine except when you're on a 4k monitor and you max
screen but only have a dinky intel integrated GPU.

At a reasonable screen size, like 800x600 or 1200x800, simulate.cpp is fine
(60hz) but this viz is maybe 15 fps. rlopt's visualizer was also at 60hz.

**Comment by colinxs** [comment]
Example: [pointmass.zip](https://github.com/Lyceum/LyceumMuJoCoViz.jl/files/4051867/pointmass.zip)

**Comment by colinxs** [comment]
@klowrey post-release? It runs butter smooth given a semi-decent GPU (e.g. superdell's 980 is totally fine), but i'm worried initial users would be turned off if they try to run this on integrated graphics.

**Comment by klowrey** [comment]
I’ll take a peek into this today to guess where the issue is.

**Comment by colinxs** [comment]
fixed in #15
